In [1]:
import numpy as np 
import pandas as pd

In [32]:
dataset_train=pd.read_csv('D:/lib/creditscore/train.csv')
dataset_test=pd.read_csv('D:/lib/creditscore/test.csv')

C:\Users\vigne\AppData\Local\Temp\ipykernel_6384\2259057662.py:1: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset_train=pd.read_csv('D:/lib/creditscore/train.csv')


In [4]:
clean_one=dataset_train[['Age','Occupation','Annual_Income','Monthly_Inhand_Salary', 
                       'Num_Bank_Accounts','Num_Credit_Card','Interest_Rate','Num_of_Loan',
                      'Changed_Credit_Limit','Num_Credit_Inquiries','Credit_Mix',
                      'Outstanding_Debt','Total_EMI_per_month']]
clean_two=dataset_train[['Delay_from_due_date', 'Num_of_Delayed_Payment','Credit_Utilization_Ratio',
                         'Credit_History_Age','Amount_invested_monthly',
                      'Payment_Behaviour','Monthly_Balance','Credit_Score']]

# DATA CLEANING

##### clean_one

In [20]:
for column in clean_one.columns:
    clean_one[column]=clean_one[column].replace('_','',regex=True)
for column in clean_one.columns:
    clean_one[column]=clean_one[column].replace('',np.nan,regex=True)
for column in clean_one.columns:
    clean_one[column]=clean_one[column].fillna(method='ffill')
for column in clean_one.columns:
    clean_one[column]=clean_one[column].fillna(method='bfill')
converto={'Age':int,'Annual_Income':float,'Num_of_Loan':int,
            'Changed_Credit_Limit':float,'Outstanding_Debt':float}
clean_one=clean_one.astype(converto)

C:\Users\vigne\AppData\Local\Temp\ipykernel_12008\3304121706.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_one[column]=clean_one[column].replace('_','',regex=True)
C:\Users\vigne\AppData\Local\Temp\ipykernel_12008\3304121706.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_one[column]=clean_one[column].replace('',np.nan,regex=True)
C:\Users\vigne\AppData\Local\Temp\ipykernel_12008\3304121706.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

In [ ]:
clean_one.info()

In [22]:
n=12500
for column in clean_one.columns:
    start=0
    stop=8
    for i in range(n):
        memory=clean_one[column].iloc[start:stop]
        value=memory.value_counts()
        max_value=value.max()
        max_index=value[value==max_value].index
        min_value=value.min()
        min_index=value[value==min_value].index
        for i in max_index:
            clean_one.loc[start:stop,column]=i
            #print(clean_one[column].iloc[start:stop])
        start=start+9
        stop=stop+9

In [23]:
path='D:/lib/creditscore/clean_one.xlsx'
clean_one.to_excel(path)

##### clean_two

In [5]:
for column in clean_two.columns:
    clean_two[column]=clean_two[column].replace('_','',regex=True)
for column in clean_two.columns:
    clean_two[column]=clean_two[column].replace('',np.nan,regex=True)
for column in clean_two.columns:
    clean_two[column]=clean_two[column].fillna(method='ffill')
for column in clean_two.columns:
    clean_two[column]=clean_two[column].fillna(method='bfill')
convertoo={'Num_of_Delayed_Payment':float,'Amount_invested_monthly':float,'Monthly_Balance':float}
clean_two=clean_two.astype(convertoo)

C:\Users\vigne\AppData\Local\Temp\ipykernel_6384\4184672394.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_two[column]=clean_two[column].replace('_','',regex=True)
C:\Users\vigne\AppData\Local\Temp\ipykernel_6384\4184672394.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_two[column]=clean_two[column].replace('',np.nan,regex=True)
C:\Users\vigne\AppData\Local\Temp\ipykernel_6384\4184672394.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
T

In [ ]:
clean_two.info()

In [6]:
for column in clean_two.columns:
    print(clean_two[column].dtype)
    if clean_two[column].dtype==float:
        clean_two[column]=clean_two[column].round(decimals=0)
        clean_two[column]=clean_two[column].abs()
    elif clean_two[column].dtype==object:
        pass
    else:
        clean_two[column]=clean_two[column].abs()

int64
float64
float64
object
float64
object
float64
object


In [10]:
temp=clean_two['Credit_History_Age']
temp=pd.Series(temp)
sub=temp.str.split(r'Years|and|Months',expand=True)
subb=sub[0].str.strip()+sub[2].str.strip()
result=[]
for i in subb:
    if len(i)==3:
        i=int(i)
        i=i/10
        result.append(i)
    elif len(i)==4:
        i=int(i)
        i=i/100
        result.append(i)
    else:
        i=float(i)
        result.append(i)
value=pd.Series(result)
value=value.round(decimals=0)
clean_two['Credit_History_Age']=value.values

In [11]:
path='D:/lib/creditscore/clean_two.xlsx'
clean_two.to_excel(path)

In [14]:
clean_one=pd.read_excel('D:/lib/creditscore/clean_one.xlsx',index_col=0)
clean_two=pd.read_excel('D:/lib/creditscore/clean_two.xlsx',index_col=0)

In [ ]:
data=dataset_train['Month']
clean_train=pd.concat([data,clean_one,clean_two],axis=1)

In [28]:
#clean_train['Payment_Behaviour'].unique()
place=clean_train[clean_train['Payment_Behaviour']=='!@9#%8'].index
clean_train.drop(place,inplace=True)

In [29]:
path='D:/lib/creditscore/clean_train.xlsx'
clean_train.to_excel(path)

# Machine learning 

In [4]:
import pandas as pd
import numpy as np
clean_train=pd.read_excel('D:/lib/creditscore/clean_train.xlsx',index_col=0)

In [5]:
x=clean_train.iloc[:,0:21]
y=clean_train['Credit_Score']
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
for i in x:
    if x[i].dtype==object:
        x[i]= le.fit_transform(x[i])
from sklearn.model_selection import train_test_split,GridSearchCV
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.10)

In [9]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()
grid = {
    'criterion': ['gini','entropy'],
    'max_depth': [None,10,20,30],
    'min_samples_split': [2,5,10],
    'min_samples_leaf': [1,2,4]
}
#grid_search = GridSearchCV(estimator=dtree,param_grid=grid,cv=5)
#grid_search.fit(x_train,y_train)
#y_pred=grid_search.predict(x_test)
dtree.fit(x_train,y_train)
dtree.predict(x_test)
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        Good       0.60      0.60      0.60      1621
        Poor       0.66      0.65      0.65      2649
    Standard       0.72      0.73      0.72      4970

    accuracy                           0.68      9240
   macro avg       0.66      0.66      0.66      9240
weighted avg       0.68      0.68      0.68      9240



In [6]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier()
grid = {
    'n_estimators': [100,200,300],
    'max_depth': [None,10,20],
    'min_samples_split': [2,5,10],
    'min_samples_leaf': [1,2,4],
    'max_features': ['auto', 'sqrt']
}
#grid_search=GridSearchCV(estimator=clf,param_grid=grid,cv=5,n_jobs=-1)
#grid_search.fit(x_train,y_train)
#y_pred=grid_search.predict(x_test)
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

        Good       0.76      0.65      0.70      1621
        Poor       0.76      0.75      0.75      2649
    Standard       0.78      0.82      0.79      4970

    accuracy                           0.77      9240
   macro avg       0.76      0.74      0.75      9240
weighted avg       0.77      0.77      0.77      9240

[[1057   25  539]
 [  25 1986  638]
 [ 306  609 4055]]


In [7]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes=(25,25,15),alpha=0.01)
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

        Good       0.55      0.12      0.19      1679
        Poor       0.63      0.39      0.48      2646
    Standard       0.58      0.86      0.69      4915

    accuracy                           0.59      9240
   macro avg       0.59      0.45      0.45      9240
weighted avg       0.59      0.59      0.54      9240



In [ ]:
random_search = RandomizedSearchCV(rf_model, param_distributions=param_dist, n_iter=100, cv=5, scoring='accuracy', random_state=42)
grid = {
    'hidden_layer_sizes': [(25,25,25),(25,25,15),(100,50)],
    'activation': ['tanh','relu'],
    'solver': ['lbfgs','sgd','adam'],
    'alpha': [0.0001,0.001,0.01]
}
grid_search=GridSearchCV(estimator=clf,param_grid=grid,cv=5)
grid_search.fit(x_train,y_train)
y_pred=grid_search.predict(x_test)