In [6]:
import numpy as np 
import pandas as pd
data=pd.read_csv('D:/lib/language detection/Language Detection.csv')
x=data['Text']
y=data['Language']
#cleaning
data_list=[]
import re
for i in x:
    i=re.sub(r'[!@#$%^&*()~`0-9;:",.\[\]\n]','',i)
    i=i.lower()
    data_list.append(i)
x=pd.Series(data_list)

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
cv=CountVectorizer()
X=cv.fit_transform(x)
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
model=MultinomialNB()
model.fit(x_train,y_train)
print(model.score(x_train,y_train))
y_pred=model.predict(x_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9931067843753779
[[104   0   0   3   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 100   0   1   1   0   0   0   0   0   0   0   0   0   1   0   0]
 [  0   0  93   4   1   0   0   0   0   0   0   0   0   2   0   0   0]
 [  0   0   0 296   1   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0 190   0   0   0   0   0   0   0   0   1   0   0   0]
 [  0   0   0   1   0 101   0   0   0   0   0   0   0   0   1   0   0]
 [  0   0   0   0   0   0  77   0   0   0   1   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   8   0   0   0   0   0   0   0   0   0]
 [  0   0   0   1   1   0   0   0 148   0   0   0   0   1   0   0   0]
 [  0   0   0   3   0   0   0   0   0  66   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   0   0   0 105   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   0   0   0   0 130   0   1   0   0   0]
 [  0   0   0   7   0   0   0   0   0   0   0   0 136   0   0   0   0]
 [  0   0   0   1   0   0   0   0   1   0   0   2   0 159 

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
v=TfidfVectorizer()
X=v.fit_transform(x)
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
model=MultinomialNB()
model.fit(x_train,y_train)
print(model.score(x_train,y_train))
y_pred=model.predict(x_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9833111621719676
[[ 97   0   0  13   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  59   0   7   1   0   0   0   0   0   0   0   0   0   5   0   0]
 [  0   0  99   5   2   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 284   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   2 204   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   8   0  76   0   0   0   0   0   0   0   0   1   0   0]
 [  0   0   0   6   0   0  65   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   4   0   0   0   8   0   0   0   0   0   0   0   0   0]
 [  0   0   0   2   1   0   0   0 137   0   0   0   0   2   0   0   0]
 [  0   0   0   2   0   0   0   0   0  83   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   0   0   0 123   0   0   0   0   0   0]
 [  0   0   0   4   2   0   0   0   0   0   0 143   0   1   0   0   0]
 [  0   0   0   8   0   0   0   0   0   0   0   0 117   0   0   0   0]
 [  0   0   0   5   2   0   0   0   0   0   0   1   0 173 